package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("PAS")
internal class PAS {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == gw.plugin.pas.PASMessageTransport.DEST_ID
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
